### ISSUE TITLE
[ПТ] Исправить замечания по задаче "Выгрузка/загрузка корректировок поступлений (Долгов)". 

### ISSUE THREAD

**Issue by Nika987** [perspective-solutions/general-repository#11]
1. Форма обработки "Выгрузка корректировок поступления в БП":
1.1. Убрать слово Обработка.
1.2. Написать полное название Выгрузка корректировок поступлений в БП.
1.3. Левее сместить поля по одной линии. Поднять поля чуть вверх. Уменьшить размер полей для ввода дат. Выровнять по левому краю, чтобы поля были на одной линии. (https://monosnap.com/file/xhUfeNB1w0x5ZHLpa2fnC4J024Lhiz )
1.4. Удалить верхнюю панель
1.5. В панели таблицы убрать кнопки редактирования таблицы (так как она заполняется автоматически и ничего кроме флажка выбирать не надо).
1.6. В панели таблицы добавить кнопки выбрать все флажки, снять все флажки, кнопки отбора. Кнопке "Заполнить" добавить картинку. Перенести кнопку "Выгрузить" добавить картинку СтартБизнесПроцесса . 

2. Вывести служебное сообщение "Сохранен файл выгрузки: +ПолноеИмяФайла". 
3. Выгружаемый файл в экселе не отображает корректно данные (хорошо бы использовать кодировку, которая сразу отображается нормально в экселе).
4. Убрать автозаполнение периода текущим месяцем
5. Установить сохранение значений на форме (Даты, Каталог), вывести в нижнюю панель кнопки "загрузить значения", "сохранить значения".

Стандарты разработки: [Ссылка](https://github.com/perspective-solutions/general-repository/wiki/%D0%A1%D1%82%D0%B0%D0%BD%D0%B4%D0%B0%D1%80%D1%82%D1%8B-%D1%80%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B8)

**Comment by kwas7** [comment]
Замечания учтены

**Comment by Nika987** [comment]
@kwas7 
Добрый день!)
Валерий, пожалуйста, исправьте сл. замечания:

1.	В верхней панели подписать кнопки Заполнить, Выгрузить. Картинку для кнопки Заполнить заменить на треугольник, картинку для кнопки Выгрузить оставить.
2.	 В нижней панели на кнопках убрать выражения Восстановить значение и Сохранить значение, заменить их на картинки.
3.	Убрать наименование Выгружать, сузить по ширине колонку. 
4.	В начало табл. добавить колонку нумерация строк.
5.	В верхней панели таблицы добавить кнопки отбора. 

По первым 5-ти пунктам см. вложение  https://clip2net.com/s/40oQXJF Это, как пример, как хотелось бы видеть кнопки и колонки табл.

6.	Изменить в табл. наименование ДатаСЧФ на Дата счета-фактуры.
7.	Добавить в ДФ=ггггММдд_ччммсс , чтобы при сохранении выгружаемый файл был уникальным.

**Comment by kwas7** [comment]
Замечания учтены

**Comment by Nika987** [comment]
@kwas7 
Валерий, в целом все хорошо. Завтра я сброшу некоторые замечания, но они будут касаться стандартов разработки. Если Вы еще не ознакомились с нашими стандартами разработки, пожалуйста, сделайте это. 
Спасибо!)

**Comment by Nika987** [comment]
@kwas7 
Валерий, добрый день!)
Исправьте, пожалуйста, замечания в программном коде:
1. Согласно п. 2 «В модуле формы располагаются только процедуры и функции, относящиеся к элементам формы»:
Требуется перенести в модуль объекта процедуры по заполнению таблицы и выгрузке в файл.

2. Согласно п. 3 «Модуль формы и объекта должны быть разделены на секции (вызывается из шаблонов текста сочетанием "мф" для модуля формы и "мо" для модуля объекта)»: 
Все процедуры и функции модуля необходимо разнести по секциям.	

3. Согласно п. 4 «Стандарты разработки, идентификаторы не должны содержать цифры, если только это не необходимо по смыслу»:
	Процедура КоманднаяПанель1Заполнить(Кнопка)
	Процедура КоманднаяПанель1УстановитьФлажки(Кнопка)
	Процедура КоманднаяПанель1СнятьФлажки(Кнопка)
	Необходимо убрать цифры и задать уникальное название. Например, КоманднаяПанельСписокЗаполнить.

4. Процедура КнопкаВыполнитьНажатие(Кнопка):
	ЗАпрос.Текст = "ВЫБРАТЬ
	Заменить заглавную букву А на прописную а.

**Comment by kwas7** [comment]
Замечания учтены
