### ISSUE TITLE
[ПТ] Исправить замечания по задаче "Улучшенный список печатных форм (Никитин)"

### ISSUE THREAD

**Issue by Nika987** [perspective-solutions/general-repository#12]
1. Справочник «СпискиПечатныхФорм»:
1.1. Убрать слово Справочник.

2. Списки печатных форм: Создание
2.1. Добавить панель к табличной части + кнопку "Заполнить по умолчанию". Кнопка "Заполнить по умолчанию" должна заполнять  табличную часть списком, согласно выбранному типу документа.
2.2. В табличной части убрать колонку Печатная форма. Изменить название колонки "Представление" на "Наименование", добавить в эту колонку список выбора.
2.3. Сделать, чтобы при изменении типа документа, табличная часть очищалась. 

3. Регистр «Пользователи списков печатных форм»
3.1. Добавить поле Пользователь (измерения регистра).
3.2. Убрать форму Запись Пользователи списков печатных форм.
3.3. Сделать редактирование этого регистра только в списке.

4. Печать:
4.1. Форма: 
- не выводить шапку таблицы;
- увеличить расстояние между кнопками и таблицей;
- вывести заголовок этой формы, как в типовой форме. Печать: <ПредставлениеДокумента>;
- расстояние между таблицей и нижней надписью увеличить до аналогичного в типовой форме;
- реализовать множественный выбор печатных форм и их печать

4.2. Сделать открытие формы модально.

**Comment by SanyaSkipor** [comment]
Поправил по замечаниям

**Comment by Nika987** [comment]
@SanyaSkipor 
Привет)

**Comment by Nika987** [comment]
@SanyaSkipor 
Привет)
Я посмотрела, все ок. Надо только еще три пункта доработать:
1. Кнопка Заполнить по умолчанию должна иметь картинку зеленый треугольник.

2. Списки печатных форм: Создание... 
В табличной части, при выборе печатной формы нужно чтобы ее наименование отображалось в ячейке сразу, а не после окончания редактирования.

3. Регистр «Пользователи списков печатных форм»:
При выборе списка печатных форм установить отбор по типу документа.

**Comment by SanyaSkipor** [comment]
> @SanyaSkipor
> Привет)
> Я посмотрела, все ок. Надо только еще три пункта доработать:
> 
> 1. Кнопка Заполнить по умолчанию должна иметь картинку зеленый треугольник.
> 2. Списки печатных форм: Создание...
>    В табличной части, при выборе печатной формы нужно чтобы ее наименование отображалось в ячейке сразу, а не после окончания редактирования.
> 3. Регистр «Пользователи списков печатных форм»:
>    При выборе списка печатных форм установить отбор по типу документа.

Привет) Поправил и это

**Comment by Nika987** [comment]
@SanyaSkipor 
Саша, все ок.
Спасибо)

**Comment by michaelvasilyuk** [comment]
Сдал задачу клиенту, все хорошо!
