### ISSUE TITLE
[БТС] Корректировка проводок при проведении

### ISSUE THREAD

**Issue by michaelvasilyuk** [perspective-solutions/general-repository#13]
Общая инфа по заданию: [ТЗ.docx](https://github.com/perspective-solutions/general-repository/files/2971439/default.docx)

Реализуем с помощью расширения. Догадываюсь, что потребуется создать регистр сведений, подписку на событие перед записью проводок и общий модуль.

В табличке там где указано, что договор входит в список договоров, имеется в виду, что несколько договоров соответствуют одной и той же группе номенклатуры или статье затрат. То есть списка никакого нет, просто много строк с одинаковыми параметрами, но разными договорами. Надеюсь понятно сформулировал.

Редактируем проводки, в которые входят счета 90.хх.х и 42.02 документов Реализация и Отчет комиссионера.

В тестовой базе требуется создать номенклатурные группы и статьи затрат с наименованиями, указанными в табличке. Чтобы бухгалтеру, которые это будет проверять было проще убедиться в том, что все работает. Соответствия договоров истребую и добавлю в комментарии к задаче.

**Comment by michaelvasilyuk** [comment]
Да, и нужно сделать обработочку, которая бы взяла за период документы и сделала конвертацию проводок по нашему алгоритму, чтобы не перепроводить документы, так как это займет слишком много времени. А просто перезапись проводок должна пройти быстро.

**Comment by kwas7** [comment]
Эта таблица конечна или просто пример
Если пример тогда нужен приоритет полей поиска
Может ли быть ситуация когда часть документа реализации мы меняем проводки а часть нет
Вопрос по 90.03 счету -  в нем каким образом менять номенклатурную группу(нет ссылки на номенклатуру и счет учета номенклатуры)

**Comment by michaelvasilyuk** [comment]
@kwas7 
1. это конечная таблица, приоритет поиска по очередности полей в таблице, но насколько мне известно конфликтных ситуаций быть не должно.
2. все проводки меняем индивидуально, поэтому допускаю, что такое возможно
3. уточняю по вопросу 90.03

**Comment by michaelvasilyuk** [comment]
по 90.03 и по 90.01.1 я вот что думаю. может быть нам сначала получить таблицу товаров, для каждого из них определить номенклатурную группу, а потом по итогам таблицы заново заполнить проводки, удалив те, что создал типовой механизм? то есть источником для определения номеклатурной группы будет не проводка, а заранее подготовленная таблица товаров?

**Comment by michaelvasilyuk** [comment]
по отчету комиссионера получается, что:
90.02.1 - 45.01 формируется на основании каждой строки товаров
62.01 - 90.01.1 - тоже по каждой строке
90.03 - 68.02 - свернуто в разрезе ном группы и ставки ндс

**Comment by michaelvasilyuk** [comment]
по реализации там зависимость от типа операции получается.
