### ISSUE TITLE
[ПТ] Связь улиц и районов доставки

### ISSUE THREAD

**Issue by michaelvasilyuk** [perspective-solutions/general-repository#14]
Требуется сделать так, чтобы при выборе улицы автоматически заполнялся район доставки. 

Для этого в спр РайоныДоставки создадим ТабличнуюЧасть "СписокУлиц" с реквизитом Наименование. В справочник добавим Макет, назовем его СписокУлиц, колонки: Регион, Район, Улица. Заполним этот макет на основании данных из [сайта](https://fms-reg.com/spisok-ulits-spb#adm). В форме элемента справочника сделаем кнопку "заполнить" для таблички улиц. по нажатию на кнопку берем макет, выбираем строки где Регион и название района совпадает с текущим элементом справочника, и заполним список улиц. 

В заказе покупателя при выборе улицы проверяем есть ли такой район, в котором совпадает регион и улица.

**Comment by michaelvasilyuk** [comment]
@SanyaSkipor нужно заполнить макет в районах доставки на основании сайта, что я тебе скидывал. Т.е. макет уже должен быть заполнен всеми улицами Питера.

**Comment by Nika987** [comment]
@SanyaSkipor 
Привет!)
Добавь, пожалуйста, список выбора в поле Наименование (В районе доставки: Создание).

**Comment by SanyaSkipor** [comment]
@Nika987 Привет)) А что включать в список выбора? Улицы, которые в макете совпадают с Регионом, выбранным в районе доставки, или же, как в документе ЗаказПокупателя, список улиц из регистра?

**Comment by Nika987** [comment]
@SanyaSkipor 
В список выбора необходимо включить районы доставки, которые связаны с улицами. Выбрав район доставки и нажав на копку Заполнить, в табл. части появляется список улиц, относящихся к выбранному району.

**Comment by SanyaSkipor** [comment]
@Nika987 
А зачем нам при создании нового Района доставки выбирать уже существующий? Или я не так что-то понял, поправь пожалуйста)

**Comment by michaelvasilyuk** [comment]
Ника имеет в виду, что выбрали регион, и выбираем из списка наименование района доставки.

**Comment by SanyaSkipor** [comment]
То есть из наименований районов Санкт-Петербурга?

**Comment by Nika987** [comment]
Да

**Comment by SanyaSkipor** [comment]
@Nika987 Понял, сделаю)

**Comment by SanyaSkipor** [comment]
Улицы в макет загрузил, список выбора в поле "Наименование" добавил

**Comment by Nika987** [comment]
@SanyaSkipor 
В заказе покупателей не происходит автозаполнение поля район доставки после ввода улицы и региона.
Например, я ввожу улицу Автогенная, регион Санкт-Петербург, и, как итог, происходит автозаполнение поля район доставки - Невский.

**Comment by SanyaSkipor** [comment]
> @SanyaSkipor
> В заказе покупателей не происходит автозаполнение поля район доставки после ввода улицы и региона.
> Например, я ввожу улицу Автогенная, регион Санкт-Петербург, и, как итог, происходит автозаполнение поля район доставки - Невский.

В данном случае район не заполнился, потому что из Регистра подтянулось "Автогенная ул", а в макете из сайта было "Автогенная ул.". Нужно что-то придумать, чтобы избегать подобных ситуаций

**Comment by michaelvasilyuk** [comment]
логичным было бы привести состояние макета к состоянию регистра, то есть удалить точки из макета.

**Comment by SanyaSkipor** [comment]
> логичным было бы привести состояние макета к состоянию регистра, то есть удалить точки из макета.

Просто тут дело не только в точках. К примеру, в регистре "Клинский пр-кт", а в макете "Клинский просп." И, думаю, таких много будет разных несоответствий.

**Comment by michaelvasilyuk** [comment]
в общем все сокращения улиц, проспектов и проездов)

**Comment by SanyaSkipor** [comment]
> в общем все сокращения улиц, проспектов и проездов)

Хорошо, заменю в макете

**Comment by SanyaSkipor** [comment]
Поправил обработкой все виды названий в макете в соответствии с регистром

**Comment by Nika987** [comment]
@SanyaSkipor 
При выборе улицы и региона автоподбором не заполняется автоматически район доставки. 

Район доставки заполняется только в том случае, когда из списка сам выбираешь улицу.

**Comment by SanyaSkipor** [comment]
@Nika987 А как ты автоподбором выбираешь?

**Comment by michaelvasilyuk** [comment]
вводишь "Автоген" в улице, нажимаешь интер. после этого должна подставится улица и выбраться район доставки Невский

**Comment by SanyaSkipor** [comment]
Ага, понял. Поправил это

**Comment by Nika987** [comment]
@SanyaSkipor 
Саша, все равно ничего не происходит. Прикрепляю видео:
https://monosnap.com/file/S8jsTyvcl7ARHmnCfJDgyhbOsV2hM4 

P.S. Перед тем как проверить перезагрузила 1С.

**Comment by SanyaSkipor** [comment]
@Nika987 Все исправлено)

**Comment by Nika987** [comment]
@SanyaSkipor 
С улицей Автогенная порядок, а с остальными нет) Прикрепляю видео:
https://monosnap.com/file/bpl5utbEyhdt4bF28ebHpCtoDFl8Pt

P.S. Ул. Бадаева из района доставки Невский

**Comment by SanyaSkipor** [comment]
@Nika987 Оно не сработало, потому что в справочнике "РайоныДоставки" еще были данные из старого макета (с ненужными точками). Я сейчас обновил данные в элементе "Невский"

**Comment by Nika987** [comment]
@SanyaSkipor @michaelvasilyuk 
Сейчас все ок.

**Comment by michaelvasilyuk** [comment]
Ура! Тогда сегодня ночью внедряю.

**Comment by Nika987** [comment]
@SanyaSkipor 
Подскажи, пожалуйста, где ты менял код?  Имя модуля и коммент по которому можно найти твой код?

**Comment by SanyaSkipor** [comment]
@Nika987 Откомменчено: "// ДоработкаВыборРайонаПоУлице 22.03.2019
                                              // Конец доработки
1) Справочник РайоныДоставки, ФормаЭлемента
2) Документ ЗаказПокупателя, ФормаДокумента
3) Справочник РайоныДоставки, Модуль менеджера - там весь модуль

**Comment by Nika987** [comment]
@SanyaSkipor 
Саша, пожалуйста:
1. раздели свой код на секции аккуратно, т.е.:  КонецПрцедуры - это строка конца процедуры; (т.е. перенеси коммент из этой строки)
2. Функция ПолучитьСписокУлиц... - отформатируй код  (правильные отступы).
3. Пустые строки в модуле должны разделять смысловые части кода.

https://monosnap.com/file/1H9N3X2evqEylIidE7oXuNkIYRx1tK

**Comment by SanyaSkipor** [comment]
@Nika987 
Хорошо, сейчас сделаю. Пустишь меня в конфигуратор?)

**Comment by Nika987** [comment]
@SanyaSkipor 
вышла

**Comment by SanyaSkipor** [comment]
Поправил

**Comment by Nika987** [comment]
@SanyaSkipor 
Было бы хорошо, если бы ты разделил код на секции шаблоном "модуль объекта" и поместил свои процедуры в секцию общего назначения.

**Comment by SanyaSkipor** [comment]
> @SanyaSkipor
> Было бы хорошо, если бы ты разделил код на секции шаблоном "модуль объекта" и поместил свои процедуры в секцию общего назначения.

Сделано

**Comment by Nika987** [comment]
@SanyaSkipor 
Спасибо, все аккуратно и красиво)
