### ISSUE TITLE
[ПТ] Сохранение настроек отчетов на СКД

### ISSUE THREAD

**Issue by michaelvasilyuk** [perspective-solutions/general-repository#15]
Для отчета "Сегментирование" (и в дальнейшем для других отчетов на СКД) нужно сделать механизм, позволяющий сохранять свои настройки, и загружать чужие настройки. Вроде бы механизм описанный в [статье](https://infostart.ru/public/97997/) нам подходит.

**Comment by michaelvasilyuk** [comment]
Вообще ведь стандартные отчеты УТ тоже как-то сохраняют свои настройки. может быть можно сразу взять этот механизм и использовать для отчетов на СКД

**Comment by SanyaSkipor** [comment]
Ну сохранять свои настройки и загружать их мы же можем... "Сохранить значения" и "Восстановить значения" на форме. Вопрос с чужими..

**Comment by michaelvasilyuk** [comment]
не, нам надо чтобы я сохранил настройку, а другой пользователь мог ей воспользоваться. Как в типовом механизме
![](https://clip2net.com/clip/m0/89e80-clip-38kb.png?nocache=1)

**Comment by SanyaSkipor** [comment]
Поковыряюсь пока в типовом механизме, как там сделано..

**Comment by SanyaSkipor** [comment]
В папке задания "Сегментирование" положил файлик с отчетом. Называется "Сегментирование с сохранением настроек". В этой статье, которую вы вчера скинули, по сути и используется типовой механизм. Поэтому я решил им воспользоваться)

**Comment by michaelvasilyuk** [comment]
изменению подвергся только отчет?

**Comment by michaelvasilyuk** [comment]
Саш, возьми отчет "Сегментирование с сохраненим настроек_20190322_1133" и добавь в него сохранение выбранных на форме периодов.

**Comment by michaelvasilyuk** [comment]
Клиент принял задачу, все ок
