### ISSUE TITLE
[ПТ] Отбор документов по сотруднику

### ISSUE THREAD

**Issue by michaelvasilyuk** [perspective-solutions/general-repository#16]
Требуется сделать отбор документов по сотруднику (справочник Физические лица). 

Список документов: 
- Штрафы и премии
- Прием на работу
- Увольнение

На форму списков документов вывести поле ввода "Сотрудник". При установке значения в списке должны отобраться те документы, в которых есть выбранный сотрудник в табличных частях.

**Comment by SanyaSkipor** [comment]
Сделал, можно смотреть. Процедуру в общем модуле "Интеграция" откомментил 
"// доработка 22.03.2019"

**Comment by michaelvasilyuk** [comment]
Спасибо, отлично. Ника посмотрит, отпишется.

**Comment by Nika987** [comment]
@SanyaSkipor 
1. Привести верхнюю панель для каждого вида документа в одинаковый вид:
https://monosnap.com/file/0NFVoHygsa7ERcn329BY661LMGQzcz 
	1.1. В документе Штрафы и премии убрать слово Документы;
	1.2. В документах Увольнения и Прием на работу убрать слово Добавить на кнопке Добавить;
	1.3. В документе Штрафы и премии добавить кнопку Вывести на основании;
	1.4. Поле ввода Сотрудник во всех документах сделать одинаковым:
		 поднять на уровень кнопок верхней панели, т.е. чуточку вверх;
                 https://monosnap.com/file/10BMfLB9y6xzRJ7GInePE3eMRsHjvG
		 длину поля сделать одинакового размера;
		 расположить справа от края.
                 https://monosnap.com/file/Qp5E7XYiERo1CCj2BHPAfnbPgvtChh

2. В важных местах кода поставить комментарии.

**Comment by michaelvasilyuk** [comment]
У меня тоже пожелание: поле отбора поставить слева сверху, так же как в журнале заказов отбор по номеру документа стоит.

**Comment by SanyaSkipor** [comment]
Поправил по найденным замечаниям. Хотел пораньше сделать, но тут немного отвлекли.

**Comment by Nika987** [comment]
@SanyaSkipor 
все ок
