### ISSUE TITLE
[ПТ] Печатная форма "Претензия"

### ISSUE THREAD

**Issue by Nika987** [perspective-solutions/general-repository#17]
Создать печатную форму "Претензия" в документе "Возврат товаров поставщику", 
[Шаблон файла с возвратами.xlsx](https://github.com/perspective-solutions/general-repository/files/3003697/default.xlsx)

Источники данных для печатной формы:

- Документ "Возврат товаров поставщику" из которого печатается форма
- Номенклатура - из табличной части возврата
- Документ "Уценка товаров", в котором была создана Номенклатура
- Запись в регистре накопления "Партии товаров на складах", созданная документом "Возврат товаров поставщику"
- Документ "Поступление товаров и услуг" из записи в регистре "Партии товаров на складах" из измерения "ДокументОприходования"

Шапка печатной формы:
- Дата возврата: дата документа
- Наименование контрагента, возвращающего товар: Наименование организации
- ИНН контрагента: ИНН организации
- Комментарий к возврату: в документ "Возврат товаров поставщику" добавить закладку Печать, а на нее добавить поле "Комментарий к возврату"

Табличная часть печатной формы:
- Артикул модели: Номенклатура.Артикул (на закладке "Учет")
- Полное Наименование: Номенклатура.НаименованиеПолное
- Серийный Номер: Номенклатура.СерийныйНомер (на закладке "Брак")
- Номер Акта СЦ - в табличную часть "Товары" документа "Уценка товаров" добавить поле
- Дата акта СЦ - в табличную часть "Товары" документа "Уценка товаров" добавить поле
- Причина возврата - Номенклатура.ТехОписание (на закладке "Брак")
- Кол-во: всегда 1
- № Документа покупки: ПоступлениеТоваровУслуг.Номер
- Дата документа покупки: ПоступлениеТоваровУслуг.Дата
- Стоимость: из записи в регистре "Партии товаров на складах" из ресурса "Стоимость"
- Код: СтранаПроисхождения.Код из строки табличной части "Товары" документа "Поступление товаров и услуг" 
- Страна: СтранаПроисхождения.Наименование из строки табличной части "Товары" документа "Поступление товаров и услуг" 
- Таможенная декларация: НомерГТД из строки табличной части "Товары" документа "Поступление товаров и услуг"

**Comment by SanyaSkipor** [comment]
По заданию вроде все - можно смотреть. ПечФорма называется "Претензия".

**Comment by Nika987** [comment]
@SanyaSkipor 
Исправь, пожалуйста:
1. Перенеси реквизит "Комментарий к возврату" в закладку Настройки печати.
2. Удали закладку Печать.
3. Укажи в печатной форме еще:
                № Претензии:  ВозвратТоваровПоставщику.Номер
                Дата Претензии: ВозвратТоваровПоставщику.Дата
4. Печатная форма "Претензия", привести шаблон "Претензия" в читабельный вид:
                все поля должны иметь шрифт Ариал размер шрифта 10, в строках табличной части шрифт Ариал размер шрифта 8;
                шапка таблички выделена жирным шрифтом, центрирование по вертикале и горизонтале по центру;
                убрать рамку вокруг всей печатной формы;
                по умолчанию сделать печать на альбомном листе, с автомасштабом по ширине страницы.
5. В табличной части Товары документа "Уценка товаров", добавленные поля № акта СЦ и дата акта СЦ расположить между статусом и тех описанием.

**Comment by SanyaSkipor** [comment]
Замечания поправил

**Comment by Nika987** [comment]
@SanyaSkipor 
Все ок) Единственное, поправь, пожалуйста:
Печатная форма "Претензия", в табличке шаблона сделать центрирование полей по вертикали и горизонтале по центру.
https://take.ms/Wdlak 

Подскажи, пожалуйста, где ты менял код? Имя модуля и коммент по которому можно найти твой код?

**Comment by SanyaSkipor** [comment]
Доброе утро) Поправил. В конфигурации код нигде не менял. Весь код в файле с внешней обработкой "Претензия". Файл лежит в папке с заданием "Задание 189. Претензия". Функция с печатью в модуле объекта находится

**Comment by Nika987** [comment]
@SanyaSkipor 
Привет, 
все ок, только в  конце таблицы появилась странная полоса - убери ее, пожалуйста.
https://take.ms/HjBDd

**Comment by SanyaSkipor** [comment]
Убрал)

**Comment by Nika987** [comment]
@SanyaSkipor 
В шаблоне "Претензия" в табличной части в поле Таможенная декларация исчезло центрирование полей по вертикали и горизонтале по центру. Сделай, пожалуйста, центрирование поля по вертикали и горизонтале по центру.
https://take.ms/6kfNO

**Comment by SanyaSkipor** [comment]
> @SanyaSkipor
> В шаблоне "Претензия" в табличной части в поле Таможенная декларация исчезло центрирование полей по вертикали и горизонтале по центру. Сделай, пожалуйста, центрирование поля по вертикали и горизонтале по центру.
> https://take.ms/6kfNO

Там стоит центрирование по горизонтали и вертикали, и в шапке, и в строке. Это 1С так центрирует ровно)

**Comment by Nika987** [comment]
Внесены изменения:
1. № Документа покупки: Счет-фактураполученный.Номер (на основании документа ПоступлениеТоваровУслуг)
Дата документа покупки: Счет-фактураполученный.Дата (на основании документа ПоступлениеТоваровУслуг).
2. Стоимость: Цена. из табличной части "Товары". из документа "Возврат товаров поставщику".
3. Артикул модели: Номенклатура.Код.
4. Полное наименование: Интеграция.ПолучитьРасширенноеНаименованиеНоменклатуры().
5. Артикул модели: Номенклатура.Справочник
6. Изменить количество возможных символов в документе "уценка товаров" "номера акта" аналогично"серийному номеру" того же документа.

**Comment by michaelvasilyuk** [comment]
Супер, спасибо!
