### ISSUE TITLE
[ПТ] Создание печатной формы "Накладная для сервиса"

### ISSUE THREAD

**Issue by Nika987** [perspective-solutions/general-repository#18]
Создать печатную форму "Накладная для сервисного центра" в документе "Перемещение товаров", по шаблону 
[в протор сервис накладная для сервиса 07.03.19.xlsx](https://github.com/perspective-solutions/general-repository/files/3013941/07.03.19.xlsx)

Грузоотправитель - добавить в перемещение закладку "Параметры печати" - туда реквизит Грузоотправитель, тип Справочник.Организации

Источники данных для печатной формы:
- Документ "Перемещение товаров" из которого печатается форма. 

Шапка печатной формы:
- Грузополучатель: имя склада получателя. Адрес: СкладПолучатель.Комментарий.
- Грузоотправитель: из документа "Перемещение товаров". Грузоотправитель (на закладке "Параметры печати"). 
- Дата составления: дата документа

Табличная часть печатной формы:
- № п/п
- Наименование товара: Интеграция.ПолучитьРасширенноеНаименованиеНоменклатуры(Номенклатура,Номенклатура.Наименование). 
- Бренд: Номенклатура.Бренд
- Серийный №: Номенклатура.СерийныйНомер (на закладке "Брак")
- Дефект: Номеклатура.ТехОписание (на закладке "Брак")
- Вид ремонта:Номенклатура.Статус
- Кол-во: всегда 1
- Примечание: удаляем колонку из таблички, она не нужна

**Comment by SanyaSkipor** [comment]
По заданию вроде все, можно смотреть. Файл с отчетом лежит: "Задание 191. Накладная для сервиса".

**Comment by Nika987** [comment]
@SanyaSkipor 
Исправь, пожалуйста:
1. Печатная форма "Накладная для сервиса", привести шаблон "Накладная на передачу техники" в читабельный вид:
       1.1.  в шапке печатной формы поля с указанием наименования и адреса Грузоотправителя и Грузополучателя должны иметь нижние границы, а также поле Дата составления должно иметь нижнюю границу (см. вложение);
      1.2. табличная часть должна иметь отступ слева, выровнять по уровню полей Грузоотправитель и Грузополучатель шапки (см. вложение); 
      1.3. перед словом НАКЛАДНАЯ поставить 1 tab, чтобы сместить название чуть вправо (см. вложение);
      1.4. сделать выравнивание полей Дата составления и 1 февраля 2019 г. по уровню последней колонки таблицы (см. вложение);
      https://take.ms/vS1nn 
      1.5. все поля должны иметь шрифт Ариал размер шрифта 10, в строках табличной части шрифт Ариал размер шрифта 8;
     1.6. центрирование всех полей в табличной форме по вертикале и горизонтале по центру;
     1.7. в табличной части замени слово Номер на № п/п;
     1.8. изменить тип формата на числовой, т.е. 01.01.2019.

2. В закладке "Настройки печати" поле Грузоотправитель сделать длиннее:
https://take.ms/FNRx3 

3. В важных местах кода поставь комментарии.

**Comment by SanyaSkipor** [comment]
Поправил по замечаниям

**Comment by Nika987** [comment]
@SanyaSkipor 
Саша),
по п. 2 сделай, пожалуйста, длину поля такой, как например, длина полей Подразделение, Наименование в закладке Дополнительно.

**Comment by SanyaSkipor** [comment]
Поправил, заодно с привязками получше познакомился)

**Comment by Nika987** [comment]
@SanyaSkipor 
все ок
