### ISSUE TITLE
[ПТ] Добавить реквизиты на закладку "Иерархия"

### ISSUE THREAD

**Issue by Nika987** [perspective-solutions/general-repository#21]
Добавить пять реквизитов на закладку «Иерархия» в Справочник.Номенклатура.Номенклатура:
Группа1 – самый верхний уровень; Группа2; Группа3; Группа4; Группа5
1.	Сделать установку значений этих реквизитов:
Перед записью товара в процедуре, где заполняется табчасть Родители добавить установку значений этих реквизитов, где ГруппаN = Родителю из строки N из таб части Родители.
2.	Создать обработку, которая для всей номенклатуры заполнит эти реквизиты.

**Comment by SanyaSkipor** [comment]
Сделал, обработка лежит в папке "Задание 194. Заполнение групп номенклатуры". Изменения в конфигурации в тестовой базе в модуле объекта справочника Номенклатура в процедуре ПередЗаписью откомменчены "Доработка 01.04.2019"

**Comment by Nika987** [comment]
@SanyaSkipor 
Подправь, пожалуйста:
1. В закладке "Иерархия групп" сделай две закладки: 1. Табличная часть 2. Группы
https://take.ms/nE4EU 
2. Очень долгая обработка, поэтому:
- надо сделать чтобы каждые 500 элементов фиксировать транзакцию;
```
Если НомерИтерации%500=0 Тогда 
   ЗафиксироватьТранзацию(); 
   НачатьТранзакцию(); 
КонецЕсли;
```
- надо записывать объект справочника с 
`НоменклатураОбъект.ОбменДанными.Загрузка=Истина;`
- этот код надо вставить в процедуру ПерезЗаписью справочника номенклатуры в самое начало процедуры, чтобы не выполнялся остальной код:
```
Если Источник.ОбменДанными.Загрузка  Тогда
	Возврат;
КонецЕсли;
```

**Comment by SanyaSkipor** [comment]
Поправил по замечаниям. По транзакциям немножко докрутил для дополнительной надежности)

**Comment by Nika987** [comment]
@SanyaSkipor 
все ок

**Comment by michaelvasilyuk** [comment]
Внедрил, все отлично работает!
