### ISSUE TITLE
[Вентстор] Сделать нетиповую нумерацию документов "Заказ покупателя"

### ISSUE THREAD

**Issue by Nika987** [perspective-solutions/general-repository#22]
Сделать нетиповую нумерацию документов "Заказ покупателя".

Поле “Номер” в документе “Заказ покупателя” должен определяться по формуле: [НомерСчета]/[ПорядковыйНомерЗаказаЭтогоСчета]. 

Например, номер счета 000000240, если у него два заказа, тогда номера заказов будут: "000000240/1" и "000000240/2".

**Comment by SanyaSkipor** [comment]
Сделал, можно смотреть. Процедура расположена в общем модуле "Интеграция"

**Comment by Nika987** [comment]
@SanyaSkipor 
Исправь, пожалуйста:
1. Сделать, чтобы нумерация заказа начинался с ...../1, например: 000000240/1. (Сейчас она начинается с 000000240/2).
2. Поправь, пожалуйста, код: 
     в важных местах кода поставь комментарии

**Comment by Nika987** [comment]
@SanyaSkipor 
все ок.

**Comment by michaelvasilyuk** [comment]
Внедрил, все работает!
