### ISSUE TITLE
[ПТ] Доработка обработки заполнения спец. продаж

### ISSUE THREAD

**Issue by michaelvasilyuk** [perspective-solutions/general-repository#25]
1. Актуальную версию обработки взять из рабочей базы из внешних обработок табличных частей
2. Сделать новый каталог с заданием и положить туда обработку
3. В обработке сделать две вещи:
- на уровне запроса убрать товары с брендом `Справочники.Бренд.НайтиПоКоду("160")` (MIELE)
- Добавить колонку "Использование", вывести первой в качестве флажка, добавить кнопки "УстановитьВсе", "СнятьВсе". И делать распределение только для выбранных строк. Если не выбрана ни одна строка, автоматом выбираем все строки.

**Comment by SanyaSkipor** [comment]
Сделал. Файл с обработкой лежит в папке "Задание 197. Доработка СпецПродаж"

**Comment by michaelvasilyuk** [comment]
внедрил, все ок!
