### ISSUE TITLE
[ПТ] Доработка сигнатур для УПД 

### ISSUE THREAD

**Issue by michaelvasilyuk** [perspective-solutions/general-repository#26]
во внешней печатной форме УПД у нас есть такой код:

```
	Если СсылкаНаОбъект.ЭтоСпециальнаяПродажа Тогда
		Подписант=Справочники.ФизическиеЛица.НайтиПоНаименованию("Балак Евгений Юрьевич",Истина);
		ВидОплаты=Перечисления.ВидыОплат.Безнал;
		ДатаПодписантов=СсылкаНаОбъект.Дата;
	Иначе
		Подписант=ПараметрыСеанса.ТекущийПользователь.ФизЛицо;
		ВидОплаты=Неопределено;
		ДатаПодписантов=Неопределено;
	КонецЕсли;
	СтруктураПодписантов=Интеграция.ПолучитьСтруктуруПодписантов(ЗаказПокупателя,Подписант,ОрганизацияПечати,ВидОплаты,ДатаПодписантов);
```
Суть его в том, что мы выводим подписантом УПД сотрудника Балак и его доверенность. Это кладовщик. Но проблема в том, что у них посменно работают два кладовщика. И нужно выводить того кладовщика. который работал в Дату реализации.

Для этого мы создаем регистр сведений "ПользователиЖурналаАвторизаций" (измерение "Пользователь") - в нем мы перечислим пользователей для которых будем регистрировать авторизации. Добавляем туда Балака и Штаденко.

И второй регистр "ЖурналАвторизаций" периодический в пределах секунды, измерение Пользователь. В нем мы будем регистрировать авторизации пользователей в базе, которые есть в регистре "ПользователиЖурналаАвторизаций". При начале работы системы пишем чтобы запись об авторизации добавлялась в регистр. Таким образом мы сможем понять авторизовывался тот или иной пользователь в базе в конкретный день.

Не забываем давать роли Пользователь права на запись этих регистров.

Варианта три: либо Балак, либо Штанденко, либо оба одновременно. Если оба, то берем Балака. И в приведенном выше коде изменяем алгоритм получения Подписанта.

Сохраняем в каталог с заданием обработку УПД и файл конфигурации для обновления рабочей. Актуальный файл упд надо взять из внешних обработок печати в рабочей базе.

**Comment by SanyaSkipor** [comment]
Задание сделал. Файлы лежат в папке "Задание 198. Доработка сигнатур для УПД"
