### ISSUE TITLE
[ПТ] Ограничение количества самовывозов

### ISSUE THREAD

**Issue by michaelvasilyuk** [perspective-solutions/general-repository#30]
Есть заказ покупателя, в нем есть вид доставки. Один из видов доставки "Самовывоз". Требуется сделать механизм ограничения количества проведенных заказов, у которых самовывоз указан на одну дату (желаемая дата доставки).

Этот механизм нужно применять для заказов, у которых:
Организация = ИМ Премьер Техно спб
Вид доставки = Самовывоз
Склад Группа = Радуга Мидея
День недели желаемой даты доставки: выходной день (сб, вс) или праздничный день. Можно получить из регистра "Регламентированный производственный календарь" (кажется так называется).

Если количество самовывозов на дату равно 5, то на эту дату регистрировать самовывозы уже нельзя. При проведении документа требуется сообщить "Выберете другую дату самовывоза".

**Comment by SanyaSkipor** [comment]
Задачку сделал в тестовой базе, можно смотреть

**Comment by Nika987** [comment]
@SanyaSkipor 
все ок
