### ISSUE TITLE
[РемСтройСервис] Добавить колонку "Внимание" в документ "Заявка материалов на объект"

### ISSUE THREAD

**Issue by michaelvasilyuk** [perspective-solutions/general-repository#32]
Добавить колонку "Внимание" в документ "Заявка материалов на объект". Это будет флажок после колонки "НомерСтроки". Если он выбран, выделаем строку жирным шрифтом. Если в документе есть хотя бы одна строка, где Внимание=Истина, то выделяем строку с документов в списке документов жирным.

**Comment by kwas7** [comment]
Посмотрите

**Comment by Nika987** [comment]
@kwas7 
все ок.
