### ISSUE TITLE
[ПТ] Отчет "Продажи уценки"

### ISSUE THREAD

**Issue by Nika987** [perspective-solutions/general-repository#36]
Требуется создать отчет "Продажи уценки" на СКД, который будет рассчитывать бонус менеджера на основании валовой прибыли.

Поскольку данный механизм расчета бонусов актуален только для уцененной продукции, то в отчет должны попадать только товары, принадлежащие группам номенклатуры "Уценка" и "Уценка сайта".

Отчет строится на оборотах регистра "Продажи".

В отчет должны попадать только продажи по закрытым заказам, то есть по таким заказам, которые полностью и отгружены, и оплачены. Отгрузку и Оплату заказа можно проверить в регистре "ВзаиморасчетыСКонтрагентами" в разрезе Измерения Сделка (ЗаказПокупателя). Датой закрытия заказа является момент отгрузки или оплаты, в зависимости от того, какое событие, которое закрыло регистр в 0, наступило позже. Отбор по периоду в отчете действует именно на дату закрытия заказа.

Группировки:
- ГоловнаяОрганизация (ПродажиОбороты.Организация.ГоловнаяОрганизация)
- Менеджер (ПродажиОбороты.ЗаказПокупателя.Ответственный)
- ЗаказПокупателя (ПродажиОбороты.ЗаказПокупателя)
- Номенклатура (ПродажиОбороты.Номенклатура)

Реквизиты:
- Дата оплаты заказа покупателя (если оплат несколько, то последнюю)
- Дата отгрузки заказа покупателя (если реализаций несколько, то последнюю)

Показатели:
- Количество
- Сумма продажи
- Себестоимость (из регистра ПродажиСебестоимость, можно посмотреть как реализовано в типовом отчете "ВаловаяПрибыль")
- Валовая прибыль = СуммаПродажи - Себестоимость
- Расчетный бонус = 16% от ВаловойПрибыли (рассчитывать только для группировки Номенклатура)
- Фиксированный бонус (рассчитывать только для группировки Номенклатура), по вхождению размера валовой прибыли в диапазон (>, <=):
  - до 1 000 р. = 30 р.
  - 1 000 - 3 000 р. = 100 р.
  - 3 000 - 10 000 р. = 300 р.
  - 10 000 - 50 000 р. = 800 р.
  - 50 000 - 100 000 р. = 1 200 р.
  - выше 100 000 р. = 2 000 р.
- Бонус - наибольшее значение из расчетного и фиксированного бонуса.

Отборы на форме отчета:
- ГоловнаяОрганизация
- Документ продажи
- Заказ покупателя
- Номенклатура
- Менеджер

Пример расчета:
![be413-clip-22kb](https://user-images.githubusercontent.com/48488168/56507434-f6c9de00-6529-11e9-94b4-eec0918db7b9.png)

**Comment by Nika987** [comment]
@kwas7 
Пожалуйста, исправьте замечания:
1. Отчет должен иметь две закладки: отбор и отчет. В качестве примера посмотрите Отчет по сегментированию (в каталоге задания).
2. На закладке отбор должен быть период отчета.
3. На закладке отбор должны быть отборы, как в отчете по сегментированию.
4. В верхней панели отчета убрать ненужные кнопки, см. вложение: https://monosnap.com/file/nDWWz8guhPG9n6hDqM8YjeWQAK9tcv
5. Запретить выводить отчет без указания периода.
6. Дата оплаты и Дата реализации перенести в Заказ покупателя, см. вложение: 
https://take.ms/vBVxQ
7. Показатели отчета должны выводиться на каждом уровне, суммируя предыдущий уровень. Кроме показателей Расчетный бонус и фиксируемый бонус, он выводится только на уровне Номенклатуры.
8. Количество округлить до целых чисел.
9. Сумма продажи, Себестоимость, Валовая прибыль, Расчетный бонус, Фиксированный бонус, Бонус - числа должны иметь два знака после запятой.
10. Если число отрицательное выделить его красным цветом.
11. Фиксированный бонус должен быть всегда. Если предыдущие показатели с минусом, расчет фиксированного бонуса брать из продажи до 1 000 р. = 30 р. см. вложение: https://monosnap.com/file/3YiSowhWSxkU9zclzQXuddnQ9JhMla . 
12. Не во всех случаях выводится дата оплаты, см. вложение: https://take.ms/ZU0no. Должна выводится всегда.

**Comment by Nika987** [comment]
@kwas7 
1. Нет отборов на закладке отбор:
Отборы на форме отчета:
ГоловнаяОрганизация
Документ продажи
Заказ покупателя
Номенклатура
Менеджер
2. Не выводится показатель отчета Бонус на уровнях Организация, Менеджер, Заказ покупателя:
https://take.ms/HpPj1

**Comment by kwas7** [comment]
Изменил

**Comment by Nika987** [comment]
@kwas7 
все ок
