### ISSUE TITLE
[ПТ] Заполнение номеров ГТД в реализациях

### ISSUE THREAD

**Issue by michaelvasilyuk** [perspective-solutions/general-repository#42]
Требуется сделать заполнение номера ГТД в реализациях перед записью документа по алгоритму: берем самое позднее предшествующее реализации поступление номенклатуры, где указан ГТД и записываем его в ТЧ.

- Сделать проверку, чтобы если номер ГТД заполнен, то перезаполнение не происходило
- Дата номера ГТД должна быть строго меньше, чем дата реализации

**Comment by Nika987** [comment]
@SanyaSkipor 
все ок
