### ISSUE TITLE
[ПТ] Отчет "Сегментирование"

### ISSUE THREAD

**Issue by michaelvasilyuk** [perspective-solutions/general-repository#8]
Шаблон отчета в приложенном файле, который прислал клиент. В файле с настройками описаны отборы, которые они хотят видеть. Реализуем на СКД.

[Шаблон сегментирование.xlsx](https://github.com/perspective-solutions/general-repository/files/2960937/default.xlsx)
[настройки шаблона отчета сегментирования.xlsx](https://github.com/perspective-solutions/general-repository/files/2960942/default.xlsx)

**Comment by SanyaSkipor** [comment]
Этот отчет с нуля нужно сделать? Или есть заготовка?

**Comment by michaelvasilyuk** [comment]
в конфе есть отчет "Отчет по плану продаж по организациям". Из него можно кое-что, но лучше писать его с нуля.

**Comment by SanyaSkipor** [comment]
Пока осмысливаю задание. Там есть несколько полей со словом "Рынок". Это определенный склад или что это?

**Comment by michaelvasilyuk** [comment]
Рынок, это такой элемент справочника Организации, в котором ЭтоРозничнаяТочка=Истина

**Comment by michaelvasilyuk** [comment]
Еще один момент: колонка План берется из регистра "ПланПродаж", в отличие от отчета по плану продаж по организациям, где используется два регистра по планам.

**Comment by SanyaSkipor** [comment]
А что имеется ввиду под полем "Рекомендуемый остаток рынка"?

**Comment by michaelvasilyuk** [comment]
регистр сведений "РекомендуемыеОстаткиТоваров". Там разрез склада, бренда и номенклатуры. Склад соединяется с Организацией через Склад.Организация

**Comment by SanyaSkipor** [comment]
А чем отличаются "ПланПродажПоКоличеству" И "ПланПродажПоКоличеству По Компании"? По чем первое поле еще разрезается, не совсем понимаю

**Comment by michaelvasilyuk** [comment]
ПланПродажПоКоличеству - в разрезе организации, а вторая колонка по всем организациям по компании

**Comment by SanyaSkipor** [comment]
Ааа, точно, не увидел сразу, что еще по организациям группируем. Тогда еще вопрос: 

> Еще один момент: колонка План берется из регистра "ПланПродаж", в отличие от отчета по плану продаж по организациям, где используется два регистра по планам.

Может, из регистра "ПланПродажПоОрганизациям"? Потому что у нас есть и колонка "ПланПродажПоКоличеству" в разрезе организаций..

**Comment by michaelvasilyuk** [comment]
@SanyaSkipor нет, план продаж по организациям это план по суммам в разрезе групп номенклатуры,  регистр ПланПродаж, который тоже в разрезе организации, это план в разрезе товаров помодельно и по количеству

**Comment by SanyaSkipor** [comment]
> @SanyaSkipor нет, план продаж по организациям это план по суммам в разрезе групп номенклатуры, регистр ПланПродаж, который тоже в разрезе организации, это план в разрезе товаров помодельно и по количеству

Да, вижу. Сразу посмотрел на регистр ПланыПродаж, там без разреза по Организации

**Comment by SanyaSkipor** [comment]
Я планирую насобирать кучу временных таблиц, собрав все данные, которые нужны, а потом их соединить. Нормальный план?

**Comment by michaelvasilyuk** [comment]
@SanyaSkipor сейчас в базе небольшая путаница с этими регистрами, поскольку клиент уходит от старой архитектуры, и переходит к новой.

**Comment by michaelvasilyuk** [comment]
> Я планирую насобирать кучу временных таблиц, собрав все данные, которые нужны, а потом их соединить. Нормальный план?

Отличный план. Не забывай индексировать таблицы по соединяемым полям

**Comment by SanyaSkipor** [comment]
> > Я планирую насобирать кучу временных таблиц, собрав все данные, которые нужны, а потом их соединить. Нормальный план?
> 
> Отличный план. Не забывай индексировать таблицы по соединяемым полям

Хорошо, учту

**Comment by SanyaSkipor** [comment]
Во всех полях, связанных с рынком, мы отбираем то, где Склад принадлежит Организации с ЭтоРозничнаяТочка = Истина?

**Comment by SanyaSkipor** [comment]
И свободный остаток - это разница между Остатки на Складах и ТоварыВРезервеНаСкладах?

**Comment by michaelvasilyuk** [comment]
> Во всех полях, связанных с рынком, мы отбираем то, где Склад принадлежит Организации с ЭтоРозничнаяТочка = Истина?

Уточнение от заказчика: он употребил слово "рынок", а имел в виду "Организация". То есть никаких отборов по ЭтоРозничнаяТочка нам не нужно. Единственный момент: Склад для ИМ Премьер-Техно нужно жестко привязать СкладЛихоборы

**Comment by michaelvasilyuk** [comment]
> И свободный остаток - это разница между Остатки на Складах и ТоварыВРезервеНаСкладах?

это верно

**Comment by SanyaSkipor** [comment]
> > Во всех полях, связанных с рынком, мы отбираем то, где Склад принадлежит Организации с ЭтоРозничнаяТочка = Истина?
> 
> Уточнение от заказчика: он употребил слово "рынок", а имел в виду "Организация". То есть никаких отборов по ЭтоРозничнаяТочка нам не нужно. Единственный момент: Склад для ИМ Премьер-Техно нужно жестко привязать СкладЛихоборы

Не совсем понял, что значит жестко привязать?

**Comment by michaelvasilyuk** [comment]
например есть поле "Свободый остаток рынки". имеется в виду свободный остаток на складе организации. но у ИМ Премьер техно нет собственного склада, где Склад.Организация = ИМ ПТ. поэтому нужно указать, что для организации ИМ ПТ - склад это Лихоборы.

**Comment by SanyaSkipor** [comment]
Что-то вроде этого?
 ВЫБОР
		КОГДА ТоварыВРезервеНаСкладахОстатки.Склад = &СкладЛихОборы
			ТОГДА &ИМПремьертехно
		ИНАЧЕ ТоварыВРезервеНаСкладахОстатки.Склад.Организация
	КОНЕЦ КАК Организация

**Comment by michaelvasilyuk** [comment]
@SanyaSkipor именно так

**Comment by SanyaSkipor** [comment]
А чем отличаются поля "Свободно на рынке" и "Свободный остаток рынки"?

**Comment by SanyaSkipor** [comment]
И что значит поле "Доступно у поставщика"?

**Comment by michaelvasilyuk** [comment]
Доступно у поставщика: ![](https://clip2net.com/clip/m0/f71f4-clip-9kb.png?nocache=1)

Этот код есть в старом отчете по плану продаж. положил его в каталог с заданием: R:\Для всех\Каталог разработок\Задания\Задание 181. Отчет Сегментирование

Группа виртуальных складов получается:  Интеграция.ПолучитьГруппуВиртуальныхСкладов()

**Comment by michaelvasilyuk** [comment]
> А чем отличаются поля "Свободно на рынке" и "Свободный остаток рынки"?

Первое - это свободный остаток на конкретном рынке
Второе - свободный остаток в совокупности на всех организациях, где ЭтоРозничнаяТочка=Истина

**Comment by SanyaSkipor** [comment]
> > А чем отличаются поля "Свободно на рынке" и "Свободный остаток рынки"?
> 
> Первое - это свободный остаток на конкретном рынке
> Второе - свободный остаток в совокупности на всех организациях, где ЭтоРозничнаяТочка=Истина

Хорошо, я понял. Так а Вы вчера писали, что под рынками пользователь имел ввиду Организации

> > Во всех полях, связанных с рынком, мы отбираем то, где Склад принадлежит Организации с ЭтоРозничнаяТочка = Истина?
> 
> Уточнение от заказчика: он употребил слово "рынок", а имел в виду "Организация". То есть никаких отборов по ЭтоРозничнаяТочка нам не нужно. Единственный момент: Склад для ИМ Премьер-Техно нужно жестко привязать СкладЛихоборы

Для этого поля все-таки нужно будет это условие?

**Comment by michaelvasilyuk** [comment]
@SanyaSkipor да, конкретно в случае поля "Свободный остаток рынки" имеется в виду реально остаток на розничных точках.  А "Свободно на рынке" это имеется в виду на любой Организации. Давай назовем это поле "Свободный остаток *на организации*" просто без "на рынке". а то путает.

**Comment by michaelvasilyuk** [comment]
@SanyaSkipor уточнил у клиента, он хочет тогда чтобы это поле было "Свободный остаток на организации"

**Comment by SanyaSkipor** [comment]
> @SanyaSkipor уточнил у клиента, он хочет тогда чтобы это поле было "Свободный остаток на организации"

Хорошо. А отборы по номенклатуре в запросе ставить, чтоб была в плане продаж, как в прошлом отчете? Или как?

**Comment by michaelvasilyuk** [comment]
отбор по номенклатуре нужен, да. и вот еще во втором файле какие они хотят отборы: ![](https://clip2net.com/clip/m0/9a992-clip-9kb.png?nocache=1)

**Comment by SanyaSkipor** [comment]
А по ценам: РРЦ, BASE, Закупочная понятно. ЯМ10 - это Яндекс 10 или какая? И с полями Маржа поясните пожалуйста, это разница относительно закупочной?

**Comment by michaelvasilyuk** [comment]
ЯМ10 - это Яндекс 10

клиент прислал:
Маржа РРЦ = (РРЦ-ЗАкупочная)/РРЦ
Маржа BASE = (Base-закупочная)/BASE
Маржа ЯМ10 = (ЯМ10-закупочная)/ЯМ10

просто маржи там быть не должно. это он ошибся. вместо нее Маржа ЯМ10

**Comment by SanyaSkipor** [comment]
Хорошо, а поля "Разница по количеству" И "Процент выполнения по количеству"?

**Comment by michaelvasilyuk** [comment]
глянь там в файле есть формула. это разность и отношение между планом и фактом продаж

**Comment by SanyaSkipor** [comment]
> глянь там в файле есть формула. это разность и отношение между планом и фактом продаж

Ага, вижу

**Comment by SanyaSkipor** [comment]
Подскажите, а отборы есть в плане и есть на складах, что имеется ввиду? Организация или компания?

**Comment by michaelvasilyuk** [comment]
Есть на складе - по компании
Есть в плане делаем два отбора: есть в плане организации, есть в плане по компании

**Comment by SanyaSkipor** [comment]
А есть продажи?

**Comment by michaelvasilyuk** [comment]
по компании в целом. во всех отборах давай явно напишем, что отбор **по компании** или **по организации**. а то они запутаются

**Comment by SanyaSkipor** [comment]
> по компании в целом. во всех отборах давай явно напишем, "есть продажи **по компании**" или по организации. а то они запутаются

Хорошо, так и сделаем

**Comment by michaelvasilyuk** [comment]
Изначально соединяем Номенклатуру прямо со справочником организаций по Организация.Активная

**Comment by SanyaSkipor** [comment]
> Изначально соединяем Номенклатуру прямо со справочником организаций по Организация.Активная

Хорошо

**Comment by michaelvasilyuk** [comment]
от клиента: 

Пропала колонка "объем продаж по организации".

Остаток лих оборы - пробел лишний
Я н10 - это ЯМ10
Маржа я н10 - аналогично

Добавить колонку (отдельно как рейтинг) Бренд.

Все что количества и рубли - округлить до целых, разить на разряды.
Все что проценты - округлить до целых, вывести знак процента.

Рейтинг интернета выделить цветом: А+ яркозеленый, А зеленый, Б желтый, С бледный какой нибудь.
Рейтинг поставщика не выделяем цветом, пусть не отвлекает.

Визуально разграничить блоки. Колонки (заголовки) выделить фоном.
фон 1 с "План по организации" по "Количество продажи по организации"
Фон 2 с "План по компании" по "Остаток у поставщиков"
фон 3 Количество дополнительные продажи по организации	Количество дополнительные продажи по компании
фон 4 Цены и маржа.
Невырвиглазно) А так, чтобы разница была видна.
